
server.address=0.0.0.0
server.port=8080

client.sql.host=localhost
client.sql.port=5432
client.sql.user=rt s_admin
client.sql.password=V2FiLX]m]N]ZXg)W)#UJ
client.sql.database=rts

client.redis.connection-strings=redis://localhost:6379/1

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/doc/index.html
springdoc.swagger-ui.disable-swagger-default-url=true
