-- SQL dialect is PostgreSQL
-- 创建数据库
-- create database rts with encoding = 'UTF8';
-- 创建新用户做为数据库的管理员
-- create user rts_admin with password 'V2FiLX]m]N]ZXg)W)#UJ';
-- 创建新用户做为服务端访问数据库的用户
-- create user rts_server with password '3r6g5xfyUu8s+wnD@Vm';
-- 设置数据库所属
-- alter database rts owner to rts_admin;
-- 切换当前用户为新创建的用户(不切换的话，创建的表还是属于之前的用户，而不是新创建的用户，会导致权限问题)
-- set role rts_admin;
-- 查看当前用户是否已经是新建的用户
-- select current_user, session_user;
-- 为服务端访问数据库的用户设置表的权限

----------------------------------------------------------------------------------------------------------------------------------------------------------------

create table menu
(
    id          bigint primary key generated by default as identity,
    parent_id   bigint      not null,
    type        int         not null,
    name        text        not null,
    icon        text        not null,
    component   text        not null,
    path        text        not null,
    sort_by     int         not null,
    status      int         not null,
    remark      text        not null,
    create_by   text        not null,
    create_time timestamptz not null default current_timestamp,
    update_by   text        not null,
    update_time timestamptz not null default current_timestamp
);

comment on table menu is '菜单表';
comment on column menu.parent_id is '父级菜单ID';
comment on column menu.type is '菜单类型，1：目录，2：菜单，3：接口(所有增删改查都是接口, 用来控制读写权限)';
comment on column menu.name is '菜单名称';
comment on column menu.icon is '菜单图标';
comment on column menu.path is '路径';
comment on column menu.sort_by is '排序字段 —— 升序';
comment on column menu.status is '状态，0:禁用，1：启用，其他未定义';
comment on column menu.remark is '备注';
comment on column menu.create_by is '创建者(管理员)';
comment on column menu.create_time is '创建时间';
comment on column menu.update_by is '修改者(管理员)';
comment on column menu.update_time is '修改时间';

-- 插入基础菜单，基础菜单应不能禁用和删除
insert into menu(id, parent_id, type, name, icon, component, path, sort_by, status, remark, create_by, update_by)
values (1, 0, 1, '菜单管理', 'Menu', '', '', 1, 1, '菜单管理目录', 'admin', 'admin'),
       (2, 1, 2, '菜单列表', 'List', '', '/menu/list', 1, 1, '菜单列表菜单', 'admin', 'admin'),
       (3, 2, 3, '菜单查询', '', '', '/menu/query', 0, 1, '菜单查询接口', 'admin', 'admin'),
       (4, 2, 3, '菜单添加', '', '', '/menu/add', 0, 1, '菜单添加接口', 'admin', 'admin'),
       (5, 2, 3, '菜单修改', '', '', '/menu/update', 0, 1, '菜单修改接口', 'admin', 'admin'),
       (6, 2, 3, '菜单删除', '', '', '/menu/delete', 0, 1, '菜单删除接口', 'admin', 'admin'),
       (7, 2, 3, '菜单状态修改', '', '', '/menu/status/change', 0, 1, '菜单状态修改接口', 'admin', 'admin'),
       (8, 0, 1, '管理员', 'Role', '', '', 1, 1, '管理员目录', 'admin', 'admin'),
       (9, 8, 2, '角色列表', 'List', '', '/admin/role/list', 2, 1, '角色列表菜单', 'admin', 'admin'),
       (10, 9, 3, '角色查询', '', '', '/admin/role/query', 0, 1, '角色查询接口', 'admin', 'admin'),
       (11, 9, 3, '角色添加', '', '', '/admin/role/add', 0, 1, '角色添加接口', 'admin', 'admin'),
       (12, 9, 3, '角色修改', '', '', '/admin/role/update', 0, 1, '角色修改接口', 'admin', 'admin'),
       (13, 9, 3, '角色删除', '', '', '/admin/role/delete', 0, 1, '角色删除接口', 'admin', 'admin'),
       (14, 9, 3, '角色状态修改', '', '', '/admin/role/status/change', 0, 1, '角色状态修改接口', 'admin', 'admin'),
       (15, 9, 3, '角色权限查询', '', '', '/admin/role/authority/query', 0, 1, '角色权限查询接口', 'admin', 'admin'),
       (16, 9, 3, '角色权限修改', '', '', '/admin/role/authority/change', 0, 1, '角色权限修改接口', 'admin', 'admin'),
       (17, 8, 2, '管理员', 'List', '', '/admin/list', 3, 1, '管理员列表菜单', 'admin', 'admin'),
       (18, 17, 3, '管理员查询', '', '', '/admin/query', 0, 1, '管理员查询接口', 'admin', 'admin'),
       (19, 17, 3, '管理员添加', '', '', '/admin/add', 0, 1, '管理员添加接口', 'admin', 'admin'),
       (20, 17, 3, '管理员修改', '', '', '/admin/update', 0, 1, '管理员修改接口', 'admin', 'admin'),
       (21, 17, 3, '管理员删除', '', '', '/admin/delete', 0, 1, '管理员删除接口', 'admin', 'admin'),
       (22, 17, 3, '管理员状态修改', '', '', '/admin/status/change', 0, 1, '管理员状态修改接口', 'admin', 'admin'),
       (23, 0, 1, '设置', 'Setting', '', '', 999, 1, '设置目录', 'admin', 'admin'),
       (24, 23, 2, '详细信息', '', '', '/setting/detail', 999, 1, '详细信息菜单', 'admin', 'admin'),
       (25, 24, 3, '详细信息修改', '', '', '/setting/detail/change', 0, 1, '详细信息修改接口', 'admin', 'admin'),
       (26, 23, 2, '修改密码', '', '', '/setting/password', 999, 1, '修改密码菜单', 'admin', 'admin'),
       (27, 26, 3, '密码修改', '', '', '/setting/password/change', 0, 1, '密码修改接口', 'admin', 'admin');

insert into menu(id, parent_id, type, name, icon, component, path, sort_by, status, remark, create_by, update_by)
values (28, 0, 1, '操作记录', 'List', '', '', 2, 1, '操作记录', 'admin', 'admin'),
       (29, 28, 2, '操作记录', '', '', '/operation/record/list', 0, 1, '操作记录', 'admin', 'admin'),
       (30, 29, 3, '操作记录查询', '', '', '/operation/record/query', 0, 1, '操作记录查询', 'admin', 'admin');

-- 恢复menu表id序列
SELECT setval('menu_id_seq', (select max(id) from menu), false);

create table role
(
    id          bigint primary key generated by default as identity,
    name        text        not null,
    code        text        not null,
    status      int         not null,
    remark      text        not null,
    create_by   text        not null,
    create_time timestamptz not null default current_timestamp,
    update_by   text        not null,
    update_time timestamptz not null default current_timestamp
);

comment on table role is '角色表';
comment on column role.name is '角色名称';
comment on column role.status is '状态，0:禁用，1：启用，其他未定义';
comment on column role.remark is '备注';
comment on column role.create_by is '创建者(管理员)';
comment on column role.create_time is '创建时间';
comment on column role.update_by is '修改者(管理员)';
comment on column role.update_time is '修改时间';

-- 插入默认角色，默认ID为1，删除角色时默认角色应不能禁用和删除
insert into role(id, name, code, status, remark, create_by, update_by)
values (1, '管理员', 'ADMIN', 1, '默认角色', 'admin', 'admin');

-- 恢复role表id序列
SELECT setval('role_id_seq', (select max(id) from role), false);

create table role_menu_authority
(
    id      bigint primary key generated always as identity,
    role_id bigint not null,
    menu_id bigint not null
);

comment on table role_menu_authority is '角色菜单权限表';
comment on column role_menu_authority.role_id is '角色ID';
comment on column role_menu_authority.menu_id is '菜单ID, 没有配置就访问不了菜单或者接口，来实现权限管理';

-- 设置默认角色基本权限，修改权限时，默认角色的基础权限应不能移除
insert into role_menu_authority(role_id, menu_id)
values (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (1, 7),
       (1, 8),
       (1, 9),
       (1, 10),
       (1, 11),
       (1, 12),
       (1, 13),
       (1, 14),
       (1, 15),
       (1, 16),
       (1, 17),
       (1, 18),
       (1, 19),
       (1, 20),
       (1, 21),
       (1, 22),
       (1, 23),
       (1, 24),
       (1, 25),
       (1, 26),
       (1, 27),
       (1, 28),
       (1, 29),
       (1, 30);


create table admin
(
    id          bigint primary key generated by default as identity,
    role_id     bigint      not null,
    username    text        not null,
    password    text        not null,
    phone       text        not null,
    email       text        not null,
    nickname    text        not null,
    avatar      text        not null,
    status      int         not null,
    remark      text        not null,
    create_by   text        not null,
    create_time timestamptz not null default current_timestamp,
    update_by   text        not null,
    update_time timestamptz not null default current_timestamp
);

comment on table admin is '管理员表';
comment on column admin.role_id is '角色ID';
comment on column admin.username is '用户名';
comment on column admin.password is '密码';
comment on column admin.phone is '手机号码';
comment on column admin.email is '邮箱';
comment on column admin.nickname is '昵称';
comment on column admin.avatar is '头像';
comment on column admin.status is '状态，0:禁用，1：启用，其他未定义';
comment on column admin.remark is '备注';
comment on column admin.create_by is '创建者(管理员)';
comment on column admin.create_time is '创建时间';
comment on column admin.update_by is '修改者(管理员)';
comment on column admin.update_time is '修改时间';

--插入默认管理员，默认ID为1，默认管理员应不能禁用和删除， 密码：rts.sk.org
insert into admin(id, role_id, username, password, phone, email, nickname, avatar, status, remark, create_by, update_by)
values (1, 1, 'admin', '$2b$10$sjE9ZEaCOgMOP2I6FWXCT.b8WjTXQXcJzROJPz6tYCzb1EA6tMfCG', '', '', '管理员', '', 1, '默认管理员', 'admin', 'admin');

-- 恢复admin表id序列
SELECT setval('admin_id_seq', (select max(id) from admin), false);

create table operation_record
(
    id          bigint      not null primary key generated always as identity,
    operator_id bigint      not null,
    operator    text        not null,
    operation   text        not null,
    arguments   text        not null,
    remark      text        not null,
    login_ip    text        not null,
    create_time timestamptz not null
);

create index idx_operation_record_operator_id on operation_record (operator_id);

comment on table operation_record is '操作记录表';
comment on column operation_record.operator_id is '操作员ID';
comment on column operation_record.operator is '操作员(用户名)';
comment on column operation_record.operation is '操作, login, logout, add, update, delete, changeState等';
comment on column operation_record.arguments is '操作参数，表名，登录账号等';
comment on column operation_record.remark is '备注';
comment on column operation_record.login_ip is '操作员登录IP';
comment on column operation_record.create_time is '操作时间';

----------------------------------------------------------------------------------------------------------------------------------------------------------------

create table user_details
(
    id          bigint not null primary key generated always as identity,
    nickname    text   not null,
    avatar      text   not null,
    gender      int    not null,
    birthday    date   not null default '0001-01-01',
    create_time text   not null default current_timestamp
);

grant select, insert, update on user_details to rts_server;

comment on table user_details is '用户信息表';
comment on column user_details.nickname is '昵称';
comment on column user_details.avatar is '头像';
comment on column user_details.gender is '性别';
comment on column user_details.birthday is '出生日期';
comment on column user_details.create_time is '创建时间';


create table user_account
(
    id       bigint not null primary key,
    username text   not null,
    phone    text   not null,
    email    text   not null,
    password text not null,
    constraint unique_user_account_username unique (username),
    constraint unique_user_account_phone unique (phone),
    constraint unique_user_account_email unique (email)
);

grant select, insert, update on user_account to rts_server;

comment on table user_account is '用户账号表';
comment on column user_account.username is '用户名';
comment on column user_account.phone is '手机';
comment on column user_account.email is '邮箱';
comment on column user_account.password is '密码';


create table user_device
(
    id          bigint      not null primary key generated always as identity,
    user_id     bigint      not null,
    device_no   text        not null,
    platform    text        not null,
    serial_no   text        not null,
    create_time timestamptz not null default current_timestamp,
    constraint unique_user_device_device_no unique (device_no)
);

grant select, insert, update, delete on user_device to rts_server;

create index idx_user_device_user_id_and_serial_no on user_device (user_id, serial_no);

comment on table user_device is '用户设备表';
comment on column user_device.user_id is '用户ID';
comment on column user_device.device_no is '设备编号';
comment on column user_device.platform is '平台';
comment on column user_device.serial_no is '序列号';
comment on column user_device.create_time is '创建时间';


create table user_token
(
    id           bigint      not null primary key generated always as identity,
    user_id      bigint      not null,
    device_id    bigint      not null,
    hash         text        not null,
    status       int         not null,
    issue_time   timestamptz not null,
    expire_time  timestamptz not null,
    refresh_time timestamptz not null,
    constraint unique_user_token_user_and_device_id unique (user_id, device_id)
);

grant select, insert, update, delete on user_token to rts_server;

comment on table user_token is '刷新TOKEN表';
comment on column user_token.user_id is '用户表ID';
comment on column user_token.device_id is '设备表ID';
comment on column user_token.hash is 'HASH';
comment on column user_token.status is '状态，1：有效，0：失效';
comment on column user_token.issue_time is '发布时间';
comment on column user_token.expire_time is '过期时间';
comment on column user_token.refresh_time is '刷新时间';
