
server.address=0.0.0.0
server.port=9000

client.sql.host=localhost
client.sql.port=5432
client.sql.user=rts_admin
client.sql.password=V2FiLX]m]N]ZXg)W)#UJ
client.sql.database=rts

client.redis.host=localhost
client.redis.port=6379
client.redis.database=0

rts.admin.setting.login-conflict-strategy=com.sk.rts.application.strategy.ForceLogoutStrategy

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/doc/index.html
springdoc.swagger-ui.disable-swagger-default-url=true

logging.level.com.sk.rts.application=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.file.name=logs/admin/application.log
logging.logback.rollingpolicy.file-name-pattern=logs/user/application-%d{yyyy-MM-dd}.%i.log
